const Users = [
  // (Admin = [{ id: 1, name: "Rohullah", img: "", email: "", password: "", role: "" }]),
  // //   (Supplier = [
  //     {
  //       id: 1,
  //       name: "Ehsan Alizada",
  //       img: "",
  //       email: "",
  //       password: "",
  //       role: "",
  //       products: 145,
  //       copuons: 12,
  //     },
  //     {
  //       id: 2,
  //       name: "Baqir Amiri",
  //       img: "",
  //       email: "",
  //       password: "",
  //       role: "",
  //       products: 145,
  //       copuons: 12,
  //     },
  //     {
  //       id: 3,
  //       name: "Jawid Bemdi",
  //       img: "",
  //       email: "",
  //       password: "",
  //       role: "",
  //       products: 145,
  //       copuons: 12,
  //     },
  //     {
  //       id: 4,
  //       name: "Ali Jan Kata",
  //       img: "",
  //       email: "",
  //       password: "",
  //       role: "",
  //       products: 145,
  //       copuons: 12,
  //     },
  //   ]),
  //   (Customers = [
  //     {
  //       id: 1,
  //       name: "Khan Mohmmad",
  //       img: "",
  //       email: "",
  //       password: "",
  //       role: "",
  //       products: 145,
  //       copuons: 12,
  //     },
  //     {
  //       id: 2,
  //       name: "Taqam",
  //       img: "",
  //       email: "",
  //       password: "",
  //       role: "",
  //       products: 145,
  //       copuons: 12,
  //     },
  //     {
  //       id: 3,
  //       name: "AliJab Reza",
  //       img: "",
  //       email: "",
  //       password: "",
  //       role: "",
  //       products: 145,
  //       copuons: 12,
  //     },
  //     { id: 4, name: "John", img: "", email: "", password: "", role: "", products: 145, copuons: 12 },
  //     { id: 5, name: "Kate", img: "", email: "", password: "", role: "", products: 145, copuons: 12 },
  //     {
  //       id: 6,
  //       name: "Jenny",
  //       img: "",
  //       email: "",
  //       password: "",
  //       role: "",
  //       products: 145,
  //       copuons: 12,
  //     },
  //   ]),
];
export default Users;
